apiVersion: apps/v1
kind: Deployment
metadata:
  name: larapgsnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: larapgsnginx
  template:
    metadata:
      labels:
        app: larapgsnginx
    spec:
      containers:
      - name: larapgsnginx
        image: devlooppear/larapgsnginx:1.0.5
        ports:
        - containerPort: 9000
