apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: devlooppear/larapgsnginx:1.0.2
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: app-volume
          mountPath: /var/www
      volumes:
      - name: app-volume
        hostPath:
          path: /home/user/Codes/BookHub/deployment-ATTENTION!/backend
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
