services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: devlooppear
        ports:
            - 9000:9000
        container_name: devlooppear-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - devlooppear
            
        # image: devlooppear/larapgsnginx:1.0.5
        # container_name: larapgsnginx
        # ports:
        #     - 9000:9000
        # restart: unless-stopped
        # working_dir: /var/www/
        # volumes:
        #     - ./:/var/www
        # networks:
        #     - devlooppear

    pgsql:
        image: "postgres:15"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        networks:
            - devlooppear
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s

    nginx:
        image: nginx:alpine
        container_name: devlooppear-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - devlooppear

    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        networks:
            - devlooppear
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        networks:
            - devlooppear

networks:
    devlooppear:
        driver: bridge
