apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
spec:
  selector:
    app: pgsql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mailpit-service
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
    - name: dashboard
      protocol: TCP
      port: 8025
      targetPort: 8025
  type: NodePort
